apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
        - name: main
          env:
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: gridcapa-rabbitmq-credentials
                key: rabbitmq-user
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gridcapa-rabbitmq-credentials
                key: rabbitmq-password
