# PATH SETTINGS
path:
  logs: /opt/bitnami/elasticsearch/logs
  data: /bitnami/elasticsearch/data

# NETWORK HOST
network:
  bind_host: 0.0.0.0
http:
  port: 9200
#transport:
#  tcp:
#    port: 9300
#http.host: 0.0.0.0
# CLUSTER NAME
cluster:
  name: elasticsearch
#  initial_master_nodes:
#    - elasticsearch-0.elasticsearch-master
#
##SECURITY
xpack:
  security:
    enabled: false
  ml:
    enabled: false
# DISCOVERY SETTINGS
discovery:
  type: single-node
  seed_hosts:
    - elasticsearch

#node:
#  name: elasticsearch-0
#  master: true
#  data: true
