# PATH SETTINGS
path:
  logs: /opt/bitnami/elasticsearch/logs
  data: /usr/share/elasticsearch/data

# NODE NAME
# Already defined in the environment variable

# NETWORK HOST
network.host: 0.0.0.0
http.port: 9200
http.host: 0.0.0.0
# CLUSTER NAME
cluster:
  name: elasticsearch
#  initial_master_nodes:
#    - elasticsearch-0.elasticsearch-master
# HEAP SIZE
# See jvm.options file

# JVM HEAP DUMP PATH
# See jvm.options file

# GC LOGGING
# See jvm.options file

# TEMP DIRECTORY
# Already defined in the environment variable

#SECURITY
#xpack.security.enabled: false

# DISCOVERY SETTINGS
discovery:
  type: single-node
  seed_hosts:
    - elasticsearch

#
#ingest:
#  geoip:
#    downloader:
#      enabled: false