spring:
  elasticsearch:
    username: ${ELASTICSEARCH_USER:#{null}}
    password: ${ELASTICSEARCH_PASSWORD:#{null}}
    uris:
      - http://elasticsearch:9200
  rabbitmq:
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    addresses: rabbitmq:5672
    address-shuffle-mode: random

powsybl-ws:
  environment: dev_

  # Postgres database prefix
  database:
    host: gridcapa-postgresql
    databaseOrSchema:
      prefix: ${powsybl-ws.environment:}

  # RabbitMQ binding destination prefixes
  rabbitmq:
    destination:
      prefix: ${powsybl-ws.environment:}

  # elasticsearch index prefixes
  elasticsearch:
    index:
      prefix: ${powsybl-ws.environment:}
