- op: add
  path: /spec/tls
  value: [ { "hosts": [ "gridcapa-dev.farao-community.com" ], "secretName": "gridcapa-tls" } ]
- op: add
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: letsencrypt-prod
- op: replace
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1ssl-redirect
  value: "true"
