apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: gridsuite
    component: gridsuite-rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 15672
    - name: prometheus
      protocol: TCP
      port: 15692
    - name: amqp
      protocol: TCP
      port: 5672
  selector:
    app: gridsuite
    component: gridsuite-rabbitmq
